### ISSUE TITLE
اقتراحات حول دوال التشفير و التوافق

### ISSUE THREAD

**Issue by abderraouf-adjal** [ring-lang/ring#52]
مرحبا،
لدي بعض الاقتراحات حول دوال التشفير بهدف احتمال توافق في الكود في حال حدوث تغييرات في اللغة بسبب _دواعي أمنية كظهور عيوب في خوارزمية أو طلب من المستخدمين_.

الدالتين `Encrypt()` و `Decrypt()`
قد يتسببان في تخلخل **التوافق** في المستقبل إن تطلب تغيير الخوارزمية المستعملة.
أقترح تغيير اسم الدالة إلى صيغة تكون فيها الخوارزمية المستعملة واضحة في الكود مثل:
`Encrypt_AES256_CBC(data, key, iv)`
أو
`Encrypt(algorithm [AES256_CBC, AES256_ECB, BLOWFISH_CBC], data, key, iv)`

كذلك أشجع على جعل الخوارزمية الافتراضية AES256-GCM
لأنها تتميز بـ Authentication
تلقائي و الأداء بسبب وجود AES-NI
في المعالجات الحديثة.

يجب أن أنوه على أن المكتبة تفتقد إلى الدوال:
* HMAC (HMAC-MD5, HMAC-SHA1, HMAC-SHA2, ...).
* KDF (PBKDF2, Scrypt, Bcrypt, ...).
* random_uniform() To generate uniformly distributed random numbers.
* Public key cryptography & key-exchange.

**Comment by MahmoudFayed** [comment]
Hello
Thanks for your comments
We will provide more and better functions in the future
Greetings,
Mahmoud

**Comment by MahmoudFayed** [comment]
Please use the next group for discussion about any thing related to the language
https://groups.google.com/forum/#!forum/ring-lang
Also post in English
Greetings,
Mahmoud
